server:
  port: 80

spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - PreserveHostHeader
            - name: JwtCookieGatewayFilter
          routes:
            - id: user-service
              uri: lb://USER-SERVICE   # service-registry(Eureka)에 등록된 이름
              predicates:
                - Path=/users/**, /api/users/**       # 요청 경로 패턴
            - id: busking-service
              uri: lb://BUSKING-SERVICE
              predicates:
                - Path=/buskings/**, /api/buskings/**
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/inventories/**, /api/inventories/**
            - id: reservation-service
              uri: lb://RESERVATION-SERVICE
              predicates:
                - Path=/reservations/**, /api/reservations/**
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payments/**, /api/payments/**
            - id: admin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/admin/**
            - id: image-service
              uri: lb://IMAGE-SERVICE
              predicates:
                - Path=/api/images/**
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/notifications/**, /api/fcm/**
            - id: subscription-service
              uri: lb://SUBSCRIPTION-SERVICE
              predicates:
                - Path=/api/subscription/**
            - id: hot-busking-service
              uri: lb://HOT-BUSKING-SERVICE
              predicates:
                - Path=/api/hot-buskings/**

  data:
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}