server:
  port: 30003

spring:
  application:
    name: reservation-service

  datasource:
    url: ${RESERVATION_DB_URL:jdbc:mysql://localhost:3306/ticket_reservations}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RESERVATION_DB_USERNAME:root}
    password: ${RESERVATION_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      ack-mode: manual
    consumer:
      group-id: reservation-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

endpoints:
  ticket-reserve-busking-service:
    url: ${BUSKING_SERVICE_URL:http://127.0.0.1:30001}
  ticket-reserve-inventory-service:
    url: ${INVENTORY_SERVICE_URL:http://127.0.0.1:30002}