server:
  port: 8761   # Eureka 기본 포트

spring:
  application:
    name: service-registry

eureka:
  client:
    register-with-eureka: false   # 자신을 레지스트리에 등록하지 않음
    fetch-registry: false         # 다른 서비스 목록 가져오지 않음