server:
  port: 36666

spring:
  application:
    name: hot-busking-service

  datasource:
    url: ${HOT_BUSKING_DB_URL:jdbc:mysql://localhost:3306/hot_buskings?rewriteBatchedStatements=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${HOT_BUSKING_DB_USERNAME:root}
    password: ${HOT_BUSKING_DB_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      ack-mode: manual
    consumer:
      group-id: hot-busking-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

app:
  redis:
    hot-busking-subscription-count-key: "hot-busking:busking:%s:subscription-count"
    hot-busking-list-key: "hot-busking:list"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
