server:
  port: 36666

spring:
  datasource:
    url: ${HOT_BUSKING_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${HOT_BUSKING_DB_USERNAME}
    password: ${HOT_BUSKING_DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    listener:
      ack-mode: manual
    consumer:
      group-id: hot-busking-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

app:
  redis:
    hot-busking-subscription-count-key: ${APP_REDIS_HOT_BUSKING_SUBSCRIPTION_COUNT_KEY}
    hot-busking-list-key: ${APP_REDIS_HOT_BUSKING_LIST_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

endpoints:
  ticket-reserve-busking-service:
    url: ${BUSKING_SERVICE_URL}