server:
  port: 36666

spring:
  datasource:
    url: ${HOT_BUSKING_DB_URL:jdbc:mysql://localhost:3306/hot_buskings?rewriteBatchedStatements=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${HOT_BUSKING_DB_USERNAME:root}
    password: ${HOT_BUSKING_DB_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      ack-mode: manual
    consumer:
      group-id: hot-busking-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

app:
  redis:
    hot-busking-subscription-count-key: ${APP_REDIS_HOT_BUSKING_SUBSCRIPTION_COUNT_KEY}
    hot-busking-list-key: ${APP_REDIS_HOT_BUSKING_LIST_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

endpoints:
  ticket-reserve-busking-service:
    url: ${BUSKING_SERVICE_URL:http://127.0.0.1:30001}