server:
  port: 35555

spring:
  application:
    name: subscription-service

  datasource:
    url: ${SUBSCRIPTION_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SUBSCRIPTION_DB_USERNAME}
    password: ${SUBSCRIPTION_DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

  data:
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    listener:
      ack-mode: manual
    consumer:
      group-id: subscription-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM}
      sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_CONFIG_API_KEY}" password="${KAFKA_CONFIG_PASSWORD}";'

app:
  redis:
    notification-schedule-key: ${APP_REDIS_NOTIFICATION_SCHEDULE_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

endpoints:
  ticket-reserve-busking-service:
    url: ${BUSKING_SERVICE_URL}