server:
  port: 35555

spring:
  application:
    name: subscription-service

  datasource:
    url: ${SUBSCRIPTION_DB_URL:jdbc:mysql://localhost:3306/subscription}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SUBSCRIPTION_DB_USERNAME:root}
    password: ${SUBSCRIPTION_DB_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  redis:
    notification-schedule-key: ${APP_REDIS_NOTIFICATION_SCHEDULE_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

endpoints:
  ticket-reserve-busking-service:
    url: ${BUSKING_SERVICE_URL:http://127.0.0.1:30001}