server:
  port: 30001

spring:
  datasource:
    url: ${BUSKING_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${BUSKING_DB_USERNAME}
    password: ${BUSKING_DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM}
      sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_CONFIG_API_KEY}" password="${KAFKA_CONFIG_PASSWORD}";'

  servlet:
    multipart:
      max-file-size: 5MB      # 파일 한 개당 최대 용량
      max-request-size: 25MB  # 한 번의 요청에 담긴 총 용량 (최대 5장)

app:
  redis:
    notification-schedule-key: ${APP_REDIS_NOTIFICATION_SCHEDULE_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

endpoints:
  ticket-reserve-image-service:
    url: ${IMAGE_SERVICE_URL}
  ticket-reserve-subscription-service:
    url: ${SUBSCRIPTION_SERVICE_URL}