server:
  port: 30001

spring:
  datasource:
    url: ${BUSKING_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${BUSKING_DB_USERNAME}
    password: ${BUSKING_DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  servlet:
    multipart:
      max-file-size: 5MB      # 파일 한 개당 최대 용량
      max-request-size: 25MB  # 한 번의 요청에 담긴 총 용량 (최대 5장)

app:
  redis:
    notification-schedule-key: ${APP_REDIS_NOTIFICATION_SCHEDULE_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

endpoints:
  ticket-reserve-image-service:
    url: ${IMAGE_SERVICE_URL}
  ticket-reserve-subscription-service:
    url: ${SUBSCRIPTION_SERVICE_URL}