server:
  port: 30001

spring:
  application:
    name: busking-service

  datasource:
    url: ${BUSKING_DB_URL:jdbc:mysql://localhost:3306/ticket_events}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${BUSKING_DB_USERNAME:root}
    password: ${BUSKING_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        default_batch_fetch_size: 100

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  servlet:
    multipart:
      max-file-size: 5MB      # 파일 한 개당 최대 용량
      max-request-size: 25MB  # 한 번의 요청에 담긴 총 용량 (최대 5장)

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

endpoints:
  ticket-reserve-inventory-service:
    url: ${INVENTORY_SERVICE_URL:http://127.0.0.1:30002}
  ticket-reserve-image-service:
    url: ${IMAGE_SERVICE_URL:http://127.0.0.1:33333}
