server:
  port: 30001

spring:
  application:
    name: event-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ticket_events

  config:
    import: optional:configserver:http://localhost:9999
