server:
  port: 30001

spring:
  application:
    name: event-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ticket_events}

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}