server:
  port: 34444

spring:
  application:
    name: notification-service

  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:mysql://localhost:3306/notifications?rewriteBatchedStatements=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${NOTIFICATION_DB_USERNAME:root}
    password: ${NOTIFICATION_DB_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      ack-mode: manual
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

app:
  redis:
    geo-key: "users:location"
    active-user-key: "user:active"
  jdbc:
    batch-size: 100

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

firebase:
  service-account:
    path: "/firebase/service-account.json"