server:
  port: 34444

spring:
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:mysql://localhost:3306/notifications?rewriteBatchedStatements=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${NOTIFICATION_DB_USERNAME:root}
    password: ${NOTIFICATION_DB_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      ack-mode: manual
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

app:
  redis:
    geo-key: ${APP_REDIS_GEO_KEY}
    active-user-key: ${APP_REDIS_ACTIVE_USER_KEY}
  jdbc:
    batch-size: 100

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

firebase:
  service-account:
    path: "/firebase/service-account.json"