server:
  port: 30004

spring:
  application:
    name: payment-service

  datasource:
    url: ${PAYMENT_DB_URL:jdbc:mysql://localhost:3306/ticket_payments}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PAYMENT_DB_USERNAME:root}
    password: ${PAYMENT_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

payment:
  client-key: ${PAYMENT_CLIENT_KEY:test_ck_oEjb0gm23PL2kz61dln63pGwBJn5}
  secret-key: ${PAYMENT_SECRET_KEY:test_sk_LkKEypNArWY0gB5nqpxe3lmeaxYG}
  base-url: https://api.tosspayments.com
  confirm-endpoint: /confirm
  gateway-url: ${GATEWAY_URL:http://localhost:8080}