server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - PreserveHostHeader
            - name: JwtAuthenticationFilter
          routes:
            - id: user-service
              uri: lb://USER-SERVICE   # service-registry(Eureka)에 등록된 이름
              predicates:
                - Path=/users/**       # 요청 경로 패턴
            - id: event-service
              uri: lb://EVENT-SERVICE
              predicates:
                - Path=/events/**, /admin/events/**
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/inventory/**, /api/admin/inventory/**
            - id: reservation-service
              uri: lb://RESERVATION-SERVICE
              predicates:
                - Path=/reservations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 0ydHRc8EG9P/RJDjjPbE8dezJ0IXc8z61Y7hDZRJKkkrDW81g9FPKb0XdU5Knun3kIBEabqtzGnsNSqbufv79g==
  expiration: 3600000