name: MSA Java CI/CD with Docker Compose

on:
  push:
    branches: [ "deploy-test" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build Microservices with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :service:user:build \
                    :service:busking:build \
                    :service:inventory:build \
                    :service:reservation:build \
                    :service:payment:build \
                    :service:image:build \
                    :platform:gateway:build \
                    :platform:registry:build \
                    -x test