name: MSA Java CI/CD with Docker Compose

on:
  push:
    branches: [ "deploy-test" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build Microservices with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :service:user:bootJar \
                    :service:busking:bootJar \
                    :service:inventory:bootJar \
                    :service:reservation:bootJar \
                    :service:payment:bootJar \
                    :service:image:bootJar \
                    :platform:gateway:bootJar \
                    :platform:registry:bootJar \
                    -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}